### PR TITLE
Polish lang fixes

### PR DESCRIPTION
**Pull request by Krzycho666**
Fixed some orthographic mistakes, and changed some translations to more proper ones.
I'm wondering why there is "Camel Case From Time To Time", and "Normal way of writing" too. Also it would be much easier for me if I could see it in game - I'm not quite sure about the context from time to time.

### CODE REVIEW

**Comment by naezith** [comment]
@negative-seven Made it so you guys make sure it's good for everyone because I don't know Polish.

**Comment by Krzycho666** [comment]
@naezith I'm not sure what you mean. The question was more about why it is not coherent when it comes to big letters on the words beginnings - not only in polish but also on original english version, ie:

`		"connection_lost": "Connection Lost",
		"new_patch": "Probably a new patch is released",
		"restart": "Please Restart the Game"`

**Comment by naezith** [comment]
@Krzycho666 I see but I want to make sure you guys both agree on the "changed some translations to more proper ones" parts.

**Comment by Krzycho666** [comment]
Ok. So I assume, that we are waiting for @negative-seven to speak-up then? Most of the changes are indisputable anyways. ;)

**Comment by negative-seven** [comment]
"Uznania" -> "Autorzy" - I find that "uznania" is more descriptive, because the credits do not just have game creators, but also testers, tools, etc - they are all kinds of acknowledgements.
"Duch Mistrzostwa" -> "Najlepszy Duch" - Calling it the best ghost is misleading, since it's a par time threshold.
"patch" -> "aktualizacja" - Generally "patch" has made it into the lexicon by now, but either way works.
Stick/Trigger - I think either both should be translated, or neither, maybe not like we've done.
Line 112 - capitalisation for consistency with english.json
Homing - maybe "samonaprowadzający"
"Pole Gry" -> "Plac Zabaw" - This one just seems to make less sense?
Line 450 comma - Is that necessary there?
Line 454 commas - Previously used to mark a "zdanie wtrącone", Also, I'm not sure if commas are meant to come before "i" in this case.




I really should not submit these things at 2 in the morning.

**Comment by Krzycho666** [comment]
"Uznania" -> "Autorzy" - I've never seen in any game "Uznania", it just sounds odd and nobody says that. I think I've never used that word in that way in my entire life. I also couldn't find this form of this word in any polish language dictionary. I agree that "Autorzy" is not fully descriptive here, but I don't think there is a better word for that in polish. Definition of word "uznanie" means also something a bit different then what you seem to think ( also by dictionary definition ). It also seems to sound quite archaic.

"Duch Mistrzostwa" -> "Najlepszy Duch"  - again I've never seen anybody writinng that way in any game with ghost runs or ghost replays. Maybe I don't get the proper context, since I didn't have a chance to play the game itself, but "Duch Mistrzostwa" sounds more like "The ghost of the championship" to me.

"patch" -> "aktualizacja" - I've been looking for the reference on official polish PS4, XBOX 360, XBOX One, Battle.net sites and they all use polish word "aktualizacja" when they write about game updates. "Patch" seems to be used in more colloquial texts, and when to friends talk to each other.

Stick/Trigger - I'm full time game developer by day for a couple of years now, and I hear words "gałka" and "trigger" all the time. On the other hands Sony and Microsoft officially calls them "drążek" and "spust". What do you think?

Line 112 - capitalisation for consistency with english.json - For me it's fine. I just don't get why it's inconsistent on original English version too.

Homing - Right. "Samonaprowadzający" is better.

"Pole Gry" -> "Plac Zabaw" - simillar to prev ones. Never seen "pole gry" in any game.  I agree that "plac zabaw" is quite literal translation, but seems to be way better then "pole gry" to me.

Line 450 comma - It's ok to me. Try to read the whole 450-451 outloud.
Line 454 commas - I'm pretty sure it's 100% correct
( https://sjp.pwn.pl/poradnia/haslo/Czy-nie-stawia-sie-przecinka-przed-i;12114.html )

**Pull request merged**
